version: "3"
services:
  vue:
    build:
      context: ./docker/vue
    container_name: iss-vue
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    command: sh -c "cd assets && yarn install && yarn serve"

  go:
    build:
      context: ./docker/go
    container_name: iss-go
    ports:
      - 8082:8082
    volumes:
      - .:/go/src
    working_dir: /go/src/app
    tty: true
    command: fresh
    #command: bash -c "cd app && realize start --server"

  nginx:
    image: nginx
    depends_on:
      - go
    container_name: iss-nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
