version: "3"
services:
  vue:
    build:
      context: ./docker/vue
    container_name: skill-set-vue
    ports:
      - 8080:8080
    volumes:
      - ./docker/vue:/app
    working_dir: /app
    tty: true
    command: sh -c "yarn install && yarn serve"

  go:
    container_name: skill-set-go
    links:
      - mysql
    build:
      context: ./docker/go
    depends_on:
      - mysql
    ports:
      - 8082:8082
    volumes:
      - ./docker/go:/go
    working_dir: /go
    environment:
      - "GOPATH=/go/app"
    tty: true
    #command: fresh
    command: sh -c "go run main.go"

  mysql:
    image: mysql:5.7
    volumes:
      - ./db/db-data:/var/lib/mysql
      - ./db/mysql/init/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    container_name: skill-set-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  nginx:
    image: nginx
    depends_on:
      - go
    container_name: skill-set-nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
# volumes:
#   db-data:
#     driver: local
