FROM golang:1.13.1-alpine

# COPY src/app /go/src/app 

ENV GO111MODULE=on

RUN apk update && \
    apk add emacs curl git && \
    apk add mysql-client vim && \
    go get github.com/pilu/fresh && \
    go get github.com/go-sql-driver/mysql && \
    go get -u github.com/gin-gonic/gin && \
    go get github.com/jinzhu/gorm && \
    go get github.com/gorilla/mux && \
    go get github.com/gin-contrib/cors
    # go get -tags 'mysql' -u github.com/golang-migrate/migrate/cmd/migrate && \