FROM node:latest

RUN apt-get update && apt-get install -y curl apt-transport-https wget && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install -y yarn

RUN yarn global add @vue/cli
    #npm install -g vue-router --save &&\
    #npm install -g @mdi/js file-loader material-design-icons-iconfont --save-dev &&\
    #npm install -g vuex --save &&\